
/* /home/ronny/repos/nd100x/src/frontend/nd100wasm/nd100wasm.c */
EMSCRIPTEN_EXPORT void TerminalOutputToJS(int identCode, char c);
EMSCRIPTEN_EXPORT void SetJSTerminalOutputHandler(int enable);
EMSCRIPTEN_EXPORT void Init(int boot_smd);
EMSCRIPTEN_EXPORT int SendKeyToTerminal(int identCode, int keyCode);
EMSCRIPTEN_EXPORT int GetTerminalAddress(int terminalId);
EMSCRIPTEN_EXPORT int GetTerminalIdentCode(int terminalId);
EMSCRIPTEN_EXPORT void Setup(const char *config);
EMSCRIPTEN_EXPORT void Step(int steps);
EMSCRIPTEN_EXPORT void Stop(void);
EMSCRIPTEN_EXPORT int RemountFloppy(int unit);
EMSCRIPTEN_EXPORT int RemountSMD(int unit);
EMSCRIPTEN_EXPORT int UnmountFloppy(int unit);
EMSCRIPTEN_EXPORT int UnmountSMD(int unit);
EMSCRIPTEN_EXPORT void SetTerminalOutputCallback(int identCode, void (*callback )(int identCode, char c ));
EMSCRIPTEN_EXPORT void Dbg_SetPaused(int paused);
EMSCRIPTEN_EXPORT int Dbg_IsPaused(void);
EMSCRIPTEN_EXPORT int Dbg_StepOne(void);
EMSCRIPTEN_EXPORT int Dbg_StepOver(void);
EMSCRIPTEN_EXPORT int Dbg_StepOut(void);
EMSCRIPTEN_EXPORT int Dbg_RunWithBreakpoints(int maxSteps);
EMSCRIPTEN_EXPORT int Dbg_GetPC(void);
EMSCRIPTEN_EXPORT int Dbg_GetRegA(void);
EMSCRIPTEN_EXPORT int Dbg_GetRegD(void);
EMSCRIPTEN_EXPORT int Dbg_GetRegB(void);
EMSCRIPTEN_EXPORT int Dbg_GetRegT(void);
EMSCRIPTEN_EXPORT int Dbg_GetRegL(void);
EMSCRIPTEN_EXPORT int Dbg_GetRegX(void);
EMSCRIPTEN_EXPORT int Dbg_GetSTS(void);
EMSCRIPTEN_EXPORT int Dbg_GetPIL(void);
EMSCRIPTEN_EXPORT int Dbg_GetEA(void);
EMSCRIPTEN_EXPORT int Dbg_GetRegAtLevel(int level, int regIndex);
EMSCRIPTEN_EXPORT int Dbg_GetPANS(void);
EMSCRIPTEN_EXPORT int Dbg_GetOPR(void);
EMSCRIPTEN_EXPORT int Dbg_GetPGS(void);
EMSCRIPTEN_EXPORT int Dbg_GetPVL(void);
EMSCRIPTEN_EXPORT int Dbg_GetIIC(void);
EMSCRIPTEN_EXPORT int Dbg_GetIID(void);
EMSCRIPTEN_EXPORT int Dbg_GetPID(void);
EMSCRIPTEN_EXPORT int Dbg_GetPIE(void);
EMSCRIPTEN_EXPORT int Dbg_GetCSR(void);
EMSCRIPTEN_EXPORT int Dbg_GetALD(void);
EMSCRIPTEN_EXPORT int Dbg_GetPES(void);
EMSCRIPTEN_EXPORT int Dbg_GetPGC(void);
EMSCRIPTEN_EXPORT int Dbg_GetPEA(void);
EMSCRIPTEN_EXPORT int Dbg_GetPCR(int level);
EMSCRIPTEN_EXPORT int Dbg_GetPANC(void);
EMSCRIPTEN_EXPORT int Dbg_GetLMP(void);
EMSCRIPTEN_EXPORT int Dbg_GetIIE(void);
EMSCRIPTEN_EXPORT int Dbg_GetCCL(void);
EMSCRIPTEN_EXPORT int Dbg_GetLCIL(void);
EMSCRIPTEN_EXPORT int Dbg_GetUCIL(void);
EMSCRIPTEN_EXPORT int Dbg_GetECCR(void);
EMSCRIPTEN_EXPORT double Dbg_GetInstrCount(void);
EMSCRIPTEN_EXPORT int Dbg_GetRunMode(void);
EMSCRIPTEN_EXPORT int Dbg_GetStopReason(void);
EMSCRIPTEN_EXPORT int Dbg_ReadMemory(int addr);
EMSCRIPTEN_EXPORT void Dbg_WriteMemory(int addr, int val);
EMSCRIPTEN_EXPORT void Dbg_AddBreakpoint(int addr);
EMSCRIPTEN_EXPORT void Dbg_RemoveBreakpoint(int addr);
EMSCRIPTEN_EXPORT void Dbg_ClearBreakpoints(void);
EMSCRIPTEN_EXPORT const char *Dbg_GetBreakpointList(void);
EMSCRIPTEN_EXPORT int Dbg_AddWatchpoint(int addr, int type);
EMSCRIPTEN_EXPORT void Dbg_RemoveWatchpoint(int addr);
EMSCRIPTEN_EXPORT void Dbg_ClearWatchpoints(void);
EMSCRIPTEN_EXPORT int Dbg_GetWatchpointCount(void);
EMSCRIPTEN_EXPORT int Dbg_GetWatchpointAddr(int index);
EMSCRIPTEN_EXPORT int Dbg_GetWatchpointType(int index);
EMSCRIPTEN_EXPORT const char *Dbg_Disassemble(int startAddr, int count);
EMSCRIPTEN_EXPORT const char *Dbg_GetLevelInfo(void);
EMSCRIPTEN_EXPORT const char *Dbg_GetScopes(void);
EMSCRIPTEN_EXPORT const char *Dbg_GetVariables(int scopeId);
EMSCRIPTEN_EXPORT const char *Dbg_GetThreads(void);
EMSCRIPTEN_EXPORT const char *Dbg_GetStackTrace(void);
EMSCRIPTEN_EXPORT const char *Dbg_GetScopes(void);
EMSCRIPTEN_EXPORT const char *Dbg_GetVariables(int scopeId);
EMSCRIPTEN_EXPORT const char *Dbg_GetThreads(void);
EMSCRIPTEN_EXPORT const char *Dbg_GetStackTrace(void);
int main(int argc, char *argv[]);
