# git_stamp.cmake - regenerate the nd100x build-stamp header on every build.
#
# Invoked at BUILD time (not configure time) so the git hash and build
# timestamp in the binary are always current:
#   cmake -DOUT=<header> -DSRC_DIR=<repo root> -DVERSION=<x.y.z> -P git_stamp.cmake
#
# Rationale: multiple build directories (build/, build_linux/, ...) routinely
# diverge, and "which source state is this binary?" has cost hours of
# debugging. nd100x --version answers it in one command.

execute_process(
    COMMAND git -C "${SRC_DIR}" rev-parse --short HEAD
    OUTPUT_VARIABLE GIT_HASH
    OUTPUT_STRIP_TRAILING_WHITESPACE
    RESULT_VARIABLE GIT_RC
    ERROR_QUIET
)

if(NOT GIT_RC EQUAL 0 OR GIT_HASH STREQUAL "")
    set(GIT_HASH "unknown")
else()
    # Tracked-file modifications (unstaged or staged) mark the build dirty.
    execute_process(
        COMMAND git -C "${SRC_DIR}" diff --quiet HEAD --
        RESULT_VARIABLE DIRTY_RC
        ERROR_QUIET
    )
    if(NOT DIRTY_RC EQUAL 0)
        string(APPEND GIT_HASH "-dirty")
    endif()
endif()

string(TIMESTAMP BUILD_TIME "%Y-%m-%d %H:%M:%S")

file(WRITE "${OUT}"
"/* Auto-generated by cmake/git_stamp.cmake on every build - DO NOT EDIT. */
#ifndef ND100X_VERSION_H
#define ND100X_VERSION_H

#define ND100X_VERSION    \"${VERSION}\"
#define ND100X_GIT_HASH   \"${GIT_HASH}\"
#define ND100X_BUILD_TIME \"${BUILD_TIME}\"

#endif
")
